name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        run: |
          mkdir -p assets

          curl -L -o assets/github-stats.svg \
            "https://github-readme-stats-77trj6dqx-josephmj0303s-projects.vercel.app/api?username=josephmj0303&show_icons=true&theme=radical&count_private=true"
          curl -L -o assets/top-langs.svg \
            "https://github-readme-stats-77trj6dqx-josephmj0303s-projects.vercel.app/api/top-langs?username=josephmj0303&layout=compact&theme=radical"

          # Validate SVG
          grep -q "<svg" assets/github-stats.svg || (echo "Invalid github-stats.svg" && exit 1)
          grep -q "<svg" assets/top-langs.svg || (echo "Invalid top-langs.svg" && exit 1)
          
      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add assets/*.svg
          
          git diff --cached --quiet || git commit -m "update stats"
          git push
